name: Lint, test and check types on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pull-request-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  init-env:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.set-env.outputs.node_version }}
      pnpm_version: ${{ steps.set-env.outputs.pnpm_version }}
    steps:
      - run: echo "Passing environment variables to context"

      - name: Checkout code
        uses: actions/checkout@v4

      - id: set-env
        uses: ./.github/actions/env-versions

  eslint:
    needs: [init-env]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get environment versions
        id: env
        uses: ./.github/actions/env-versions

      - name: Set up environment
        uses: ./.github/actions/setup-pnpm-node-deps
        with:
          node_version: ${{ steps.env.outputs.node_version }}
          pnpm_version: ${{ steps.env.outputs.pnpm_version }}

      - name: Run ESLint
        run: |
          pnpm lint

  type-check:
    needs: [init-env]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get environment versions
        id: env
        uses: ./.github/actions/env-versions

      - name: Set up environment
        uses: ./.github/actions/setup-pnpm-node-deps
        with:
          node_version: ${{ steps.env.outputs.node_version }}
          pnpm_version: ${{ steps.env.outputs.pnpm_version }}

      - name: Build packages
        run: |
          pnpm build:packages

      - name: Run type-check
        run: |
          pnpm type-check

  stylelint:
    needs: [init-env]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get environment versions
        id: env
        uses: ./.github/actions/env-versions

      - name: Set up environment
        uses: ./.github/actions/setup-pnpm-node-deps
        with:
          node_version: ${{ steps.env.outputs.node_version }}
          pnpm_version: ${{ steps.env.outputs.pnpm_version }}

      - name: Run stylelint
        run: |
          pnpm stylelint
